#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.
# Simplified wrapper for Termux

APP_HOME=$(cd "${0%/*}" && pwd)
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec java -Xmx2048m -Dorg.gradle.appname=gradlew -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
